version: '3.9'

services:
  nginx:
    container_name: nginx
    depends_on:
    - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    restart: always

#TODO: make the mariadb and wordpress folder locally before execution
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /Users/toshsharma/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/toshsharma/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
